name: Node.js CI

on:
  push:
    branches: [ master, github-action-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run format:ci
    - run: npm run build
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: npm run deploy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
