name: Node.js CI

on:
  push:
    branches: [ master, github-action-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npm run format:ci
        npm run build
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm run deploy
